name: terraform-enterprise
services:
  tfe:
    image: images.releases.hashicorp.com/hashicorp/terraform-enterprise:__TFE_VERSION__
    environment:
      TFE_LICENSE: "__TFE_LICENSE__"
      TFE_HOSTNAME: "__DOMAIN_NAME__"
      TFE_ENCRYPTION_PASSWORD: "password"
      TFE_OPERATIONAL_MODE: "external"
      TFE_DISK_CACHE_VOLUME_NAME: ${COMPOSE_PROJECT_NAME}_terraform-enterprise-cache
      TFE_TLS_CERT_FILE: /etc/ssl/private/terraform-enterprise/cert.pem
      TFE_TLS_KEY_FILE: /etc/ssl/private/terraform-enterprise/key.pem
      TFE_TLS_CA_BUNDLE_FILE: /etc/ssl/private/terraform-enterprise/bundle.pem
      TFE_IACT_SUBNETS: 49.36.138.241/32

      # Database settings
      TFE_PG_USER: "__DB_USER__"
      TFE_PG_PASSWORD: "__DB_PASSWORD__"
      TFE_PG_HOST: "__DB_HOST__"
      TFE_PG_DATABASE: "__DB_NAME__"
      TFE_DATABASE_PARAMETERS: "sslmode=require"

      # Object storage settings
      TFE_OBJECT_STORAGE_TYPE: "azure"
      TFE_OBJECT_STORAGE_S3_REGION: "__BlobStorage_REGION__"
      TFE_AZURE_STORAGE_ACCOUNT_NAME: "__BlobStorage_Name__"
      TFE_OBJECT_STORAGE_S3_USE_INSTANCE_PROFILE: "true"

    cap_add:
      - IPC_LOCK
    read_only: true
    tmpfs:
      - /tmp
      - /run
      - /var/log/terraform-enterprise
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /run/docker.sock
      - type: bind
        source: ./certs
        target: /etc/ssl/private/terraform-enterprise
      - type: bind
        source: /app
        target: /var/lib/terraform-enterprise
      - type: volume
        source: terraform-enterprise-cache
        target: /var/cache/tfe-task-worker/terraform

volumes:
  terraform-enterprise-cache:
